name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  all-cli-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: mv .env.example .env
      - run: npm ci
      - run: npm run build
      - run: npm run test:coverage
      - run: npm run lint
      - run: npm run check-format
      - run: npm run check-types
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.2.3
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: mv .env.example .env
      - uses: cypress-io/github-action@v6
        with:
          build: npm run pretest:e2e:run
          start: npm run test:e2e:run
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: 'UI - Chrome'
          config-file: cypress.json
          spec: cypress/e2e/**/*
          # working-directory: .
